[general]
import = [
	"~/.config/alacritty/themes/catppuccin-mocha.toml",
	"~/.config/alacritty/fonts/geist-mono-nf.toml",
	"~/.config/alacritty/keybindings.toml",
]

[cursor]
vi_mode_style = "Block"

[env]
TERM = "xterm-256color"

[mouse]
hide_when_typing = true

[window.padding]
x = 8
y = 8
