# [lazygit/docs](https://github.com/jesseduffield/lazygit/tree/master/docs)
# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

git:
  allBranchesLogCmds:
    - git log --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=medium
  branchLogCmd: git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --
  merging:
    args: "--no-ff"
  pagers:
    - colorArg: always
      pager: delta --paging=never --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"

gui:
  border: rounded
  expandFocusedSidePanel: true
  nerdFontsVersion: "3"
  scrollHeight: 16
  skipAmendWarning: true
  skipRewordInEditorWarning: true
  spinner:
    frames:
      - "󰄰"
      - "󰪞"
      - "󰪟"
      - "󰪠"
      - "󰪡"
      - "󰪢"
      - "󰪣"
      - "󰪤"
      - "󰪥"
      - "󰪥"
    rate: 42
  tabWidth: 2
  theme:
    activeBorderColor:
      - "#3e8fb0"
      - bold
    cherryPickedCommitBgColor:
      - "#39355200"
    cherryPickedCommitFgColor:
      - "#f6c177"
    defaultFgColor:
      - "#e0def4"
    inactiveBorderColor:
      - "#6e6a86"
    markedBaseCommitBgColor:
      - "#39355200"
    markedBaseCommitFgColor:
      - "#f6c177"
    optionsTextColor:
      - "#9ccfd8"
    searchingActiveBorderColor:
      - "#f6c177"
      - bold
    selectedLineBgColor:
      - "#393552"
    unstagedChangesColor:
      - "#6e6a86"

  authorColors:
    "*": "#ea9a97"

customCommands:
  - key: "c"
    command: "git commit -v"
    context: "global"
    description: "Commit all staged files"
    output: terminal
  - key: "u"
    command: "git reset --soft HEAD~1"
    context: "commits"
    description: "Undo last commit"
  - key: "b"
    command: "n-backup-commit --stage-all"
    context: "files"
    description: "Commit all files in stage and unstaged with a timestamp message"
  - key: "B"
    command: "n-backup-commit"
    context: "files"
    description: "Commit just staged files with a timestamp message"

keybinding:
  commits:
    renameCommit: R
    renameCommitWithEditor: r
  files:
    commitChanges: C
    commitChangesWithEditor: <disabled>

promptToReturnFromSubprocess: false
