[font]
size = 13

[font.bold]
family = "Maple Mono NF"
style = "Bold"

[font.bold_italic]
family = "Maple Mono NF"
style = "BoldItalic"

[font.italic]
family = "Maple Mono NF"
style = "Italic"

[font.normal]
family = "Maple Mono NF"
style = "Regular"

[font.offset]
x = -1
y = -2
